Add missing styledocco node module to package.json
Fix for grunt build error:

Running "styleguide" task
Generating CSS style guide
Warning: Cannot find module '../node_modules/styledocco/cli.js' Use --force to continue.

Aborted due to warnings.